---
- name: Install Docker and add user to Docker group
  hosts: all
  vars:
     account_id: "454717754853"
     repo_name: "paymob"
     region: "us-east-1"
  become: true
  tasks:

    - name: Update Ubuntu
      apt:
        update_cache: yes
        upgrade: yes
    
    - name: Set build timestamp
      set_fact:
        build_timestamp: "{{ ansible_date_time.iso8601_basic_short }}"

    - name: Clone repo
      ansible.builtin.git:
        repo: 'https://github.com/El-Zedy/DevOps-Task.git'
        dest: /home/ubuntu/DevOps-Task
        
    - name: Build Docker image from Dockerfile using shell
      command: docker build -t "{{ account_id }}.dkr.ecr.{{ region }}.amazonaws.com/{{ repo_name }}:{{ build_timestamp }}" ./DevOps-Task

    - name: Create AWS ECR
      command: aws ecr create-repository --repository-name "{{ repo_name }}"
      register: create_repo_result
      failed_when: >
        create_repo_result.rc != 0 and "RepositoryAlreadyExistsException" not in create_repo_result.stderr

    - name: Login to AWS ECR
      shell: aws ecr get-login-password --region "{{ region }}" | docker login --username AWS --password-stdin {{ account_id }}.dkr.ecr.{{ region }}.amazonaws.com/{{ repo_name }}

    - name: Push Docker image to AWS ECR
      command: docker push "{{ account_id }}.dkr.ecr.{{ region }}.amazonaws.com/{{ repo_name }}:{{ build_timestamp }}"

    - name: Add Cluster context
      command: aws eks update-kubeconfig --region us-east-1 --name EKS-Simple-Cluster-DEV

    - name: Set image URL in deployment.yaml
      lineinfile:
        path: /home/ubuntu/DevOps-Task/k8s-manifests/deployment.yaml
        regexp: '^(\s*image:\s*").+(")'
        line: '\1{{ account_id }}.dkr.ecr.{{ region }}.amazonaws.com/{{ repo_name }}:{{ build_timestamp }}\2'
        backrefs: yes

    - name: Deploy Application
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/home/ubuntu/DevOps-Task/k8s-manifests/deployment.yaml') | from_yaml }}"

    # - name: Deploy to Kubernetes
    #   community.kubernetes.k8s:
    #     kubeconfig: /home/ubuntu/.kube/config
    #     state: present
    #     src: /home/ubuntu/DevOps-Task/k8s-manifests/deployment.yaml
