---
- name: Install Docker and add user to Docker group
  hosts: all
  vars:
     account_id: "454717754853"
     repo_name: "paymob"
     region: "us-east-1"
  become: true
  tasks:

    - name: Update Ubuntu
      apt:
        update_cache: yes
        upgrade: yes
    
    - name: Set build timestamp
      set_fact:
        build_timestamp: "{{ ansible_date_time.iso8601_basic_short }}"

    - name: Clone repo
      ansible.builtin.git:
        repo: 'https://github.com/El-Zedy/DevOps-Task.git'
        dest: /home/ubuntu/DevOps-Task
        
    # - name: Build Docker image from Dockerfile using shell
    #   command: docker build -t "{{ repo_name }}":{{ build_timestamp }} ./DevOps-Task
    
    - name: Create AWS ECR
      command: aws ecr create-repository --repository-name "{{ repo_name }}"

    - name: Login to AWS ECR
      command: aws ecr get-login-password --region "{{ region }}" | docker login --username AWS --password-stdin {{ account_id }}.dkr.ecr.{{ region }}.amazonaws.com/{{ repo_name }}



